version: '2'

volumes:
  appdata-mage21-php70:
  dbdata-mage21-php70:

services:
  app:
    image: mageinferno/magento2-nginx:1.11-1
    links:
      - phpfpm
      - db
    volumes:
      - appdata-mage21-php70:/var/www/html
      - ./.composer:/srv/www/var/composer_home
      - ./AddressFinder:/var/www/html/app/code/AddressFinder
    ports:
      - 8000:80

  phpfpm:
    image: mageinferno/magento2-php:7.0.8-fpm-3
    links:
      - db
    volumes:
      - appdata-mage21-php70:/var/www/html
      - appdata-mage21-php70:/srv/www
      - ./.composer:/srv/www/var/composer_home
      - ./AddressFinder:/var/www/html/app/code/AddressFinder
      - ./AddressFinder:/srv/www/app/code/AddressFinder

  db:
    image: mariadb:10.1
    volumes:
      - dbdata-mage21-php70:/var/lib/mysql
    ports:
      - 8001:3306
    env_file: .docker/mysql.env

  setup:
    image: mageinferno/magento2-php:7.0.8-fpm-3
    command: /usr/local/bin/mage-setup
    links:
      - db
    volumes:
      - appdata-mage21-php70:/srv/www
      - ./.composer:/srv/www/var/composer_home
    environment:
      - M2SETUP_VERSION=2.1.14
    env_file: .docker/setup.env
