version: '2'

volumes:
  appdata:
  dbdata:

services:
  app:
    image: mageinferno/magento2-nginx:1.11-1
    links:
      - phpfpm
      - db
    volumes:
      - appdata:/var/www/html
      - ./.composer:/var/www/.composer
      # - ./AddressFinder:/var/www/html/app/code/AddressFinder
    ports:
      - 8000:80

  phpfpm:
    image: mageinferno/magento2-php:7.0.8-fpm-3
    links:
      - db
    volumes:
      - appdata:/var/www/html
      - appdata:/srv/www
      - ./.composer:/var/www/.composer
      # - ./AddressFinder:/var/www/html/app/code/AddressFinder
      # - ./AddressFinder:/srv/www/app/code/AddressFinder

  db:
    image: mariadb:10.1
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 8001:3306
    env_file: .env/mysql.env

  setup:
    image: mageinferno/magento2-php:7.0.8-fpm-3
    command: /usr/local/bin/mage-setup
    links:
      - db
    volumes:
      - appdata:/srv/www
      - ./.composer:/var/www/.composer
    env_file: .env/setup.env
