version: '2'

volumes:
  appdata-mage22-php70:
  dbdata-mage22-php70:

services:
  app:
    container_name: app-mage22-php70
    volumes:
      - appdata-mage22-php70:/var/www/html

  phpfpm:
    container_name: phpfpm-mage22-php70
    image: mageinferno/magento2-php:7.0.8-fpm-3
    volumes:
      - appdata-mage22-php70:/var/www/html
      - appdata-mage22-php70:/srv/www

  db:
    container_name: db-mage22-php70
    volumes:
      - dbdata-mage22-php70:/var/lib/mysql

  setup:
    container_name: setup-mage22-php70
    image: mageinferno/magento2-php:7.0.8-fpm-3
    volumes:
      - appdata-mage22-php70:/srv/www
    environment:
      - M2SETUP_VERSION=2.2.5